# Generated by Django 4.2.30 on 2026-07-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumPatSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=20)),
                ('num_pat_id', models.CharField(max_length=30)),
                ('period_key', models.CharField(max_length=20)),
                ('last_number', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'num_pat_seq',
                'indexes': [models.Index(fields=['institution_id', 'num_pat_id', 'period_key'], name='num_pat_seq_institu_33b6cb_idx')],
                'unique_together': {('institution_id', 'num_pat_id', 'period_key')},
            },
        ),
        migrations.CreateModel(
            name='NumPatMast',
            fields=[
                ('institution_id', models.CharField(db_index=True, max_length=20)),
                ('num_pat_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pattern_name', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('seq_start', models.BigIntegerField()),
                ('seq_end', models.BigIntegerField()),
                ('seq_step', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'num_pat_mast',
                'indexes': [models.Index(fields=['institution_id', 'status'], name='num_pat_mas_institu_567f7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NumPatDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_id', models.CharField(db_index=True, max_length=20)),
                ('num_pat_id', models.CharField(db_index=True, max_length=30)),
                ('token_order', models.IntegerField()),
                ('token_id', models.CharField(choices=[('PREFIX', 'Prefix'), ('SUFFIX', 'Suffix'), ('SEQ', 'Sequence'), ('YYYY', 'Year (4-digit)'), ('YY', 'Year (2-digit)'), ('MM', 'Month'), ('DD', 'Day'), ('FY', 'Financial Year'), ('STATIC', 'Static Text'), ('BRANCH', 'Branch'), ('PRODUCT', 'Product')], max_length=20)),
                ('token_value', models.CharField(blank=True, max_length=100, null=True)),
                ('seq_length', models.IntegerField(blank=True, null=True)),
                ('reset_policy', models.CharField(blank=True, choices=[('FY', 'Financial Year'), ('YEAR', 'Year'), ('MONTH', 'Month'), ('NEVER', 'Never')], max_length=20, null=True)),
                ('num_pat_status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'num_pat_details',
                'ordering': ['token_order'],
                'indexes': [models.Index(fields=['num_pat_id', 'token_order'], name='num_pat_det_num_pat_c641f4_idx'), models.Index(fields=['institution_id', 'num_pat_id'], name='num_pat_det_institu_204671_idx')],
                'unique_together': {('num_pat_id', 'token_order')},
            },
        ),
        migrations.CreateModel(
            name='NumGenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=20)),
                ('num_pat_id', models.CharField(max_length=30)),
                ('generated_number', models.CharField(max_length=200)),
                ('period_key', models.CharField(max_length=20)),
                ('context_data', models.JSONField(default=dict)),
                ('generated_by', models.CharField(max_length=50, null=True)),
                ('generated_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'num_gen_log',
                'indexes': [models.Index(fields=['institution_id', 'num_pat_id', 'generated_datetime'], name='num_gen_log_institu_06da7d_idx')],
            },
        ),
    ]
