# Generated by Django 4.2.30 on 2026-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=255)),
                ('user_designation', models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('SYSTEM_ADMINISTRATOR', 'System Administrator'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher / Faculty'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('COUNSELOR', 'Counselor'), ('IT_SUPPORT', 'IT Support')], max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('password_reset_flag', models.BooleanField(default=True)),
                ('password_cr_date', models.DateTimeField()),
                ('password_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('cr_by', models.CharField(max_length=50)),
                ('cr_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_by', models.CharField(blank=True, max_length=50, null=True)),
                ('mod_date_time', models.DateTimeField(blank=True, null=True)),
                ('user_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Locked', 'Locked')], default='Active', max_length=20)),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('institution_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentNumberControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'student_number_control',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
