# Generated by Django 4.2.30 on 2026-05-27 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=30, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_short_name', models.CharField(blank=True, max_length=50)),
                ('course_category', models.CharField(blank=True, max_length=100)),
                ('course_time_limit', models.CharField(blank=True, max_length=10)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=20)),
                ('course_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('course_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'course_master',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('for_approval', 'For Approval'), ('rejected', 'Rejected')], default='for_approval', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('payment_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('payment_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to='users.user')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.coursemaster', to_field='course_id')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('sm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_short_name', models.CharField(blank=True, max_length=50)),
                ('subject_remarks', models.CharField(blank=True, max_length=200)),
                ('subject_status', models.CharField(default='Active', max_length=20)),
                ('cr_by', models.CharField(max_length=20)),
                ('cr_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_by', models.CharField(blank=True, max_length=20, null=True)),
                ('mod_date_time', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.coursemaster', to_field='course_id')),
                ('institution', models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.institution')),
            ],
            options={
                'db_table': 'subject_master',
                'unique_together': {('course', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentVerificationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='enrollment.enrollment')),
                ('institution', models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.institution')),
            ],
            options={
                'db_table': 'payment_verification_log',
            },
        ),
        migrations.CreateModel(
            name='PapersMaster',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=20, unique=True)),
                ('paper_name', models.CharField(max_length=100)),
                ('paper_short_name', models.CharField(blank=True, max_length=20)),
                ('paper_remarks', models.CharField(blank=True, max_length=500)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('paper_status', models.CharField(default='Active', max_length=20)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.coursemaster', to_field='course_id')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers_created', to='users.user')),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers_modified', to='users.user')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.subjectmaster', to_field='subject_id')),
            ],
            options={
                'db_table': 'papers_master',
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('lu_id', models.AutoField(primary_key=True, serialize=False)),
                ('learning_unit_id', models.CharField(max_length=20, unique=True)),
                ('lu_caption', models.CharField(max_length=100)),
                ('lu_type', models.CharField(choices=[('pdf', 'PDF'), ('mp3', 'MP3'), ('mp4', 'MP4'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, null=True)),
                ('lu_mediatype', models.CharField(choices=[('File', 'File'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True)),
                ('lu_file_name', models.CharField(blank=True, max_length=100)),
                ('lu_file_location', models.CharField(blank=True, max_length=300)),
                ('lu_duration', models.TimeField(blank=True, null=True)),
                ('lu_preview_flag', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('lu_crdt', models.DateTimeField(auto_now_add=True)),
                ('lu_moddt', models.DateTimeField(blank=True, null=True)),
                ('lu_status', models.CharField(default='Active', max_length=20)),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.coursemaster', to_field='course_id')),
                ('lu_crby', models.ForeignKey(db_column='lu_crby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lu_created', to='users.user')),
                ('lu_modby', models.ForeignKey(db_column='lu_modby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lu_modified', to='users.user')),
            ],
            options={
                'db_table': 'learning_units',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='institution',
            field=models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.institution'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.user'),
        ),
        migrations.AddField(
            model_name='coursemaster',
            name='institution',
            field=models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.institution'),
        ),
        migrations.CreateModel(
            name='ChapterMaster',
            fields=[
                ('paper_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.CharField(max_length=20, unique=True)),
                ('chapter_name', models.CharField(max_length=60)),
                ('chapter_short_name', models.CharField(blank=True, max_length=10)),
                ('chapter_status', models.CharField(default='Active', max_length=20)),
                ('cr_date_time', models.DateTimeField(auto_now_add=True)),
                ('mod_date_time', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.coursemaster', to_field='course_id')),
                ('cr_by', models.ForeignKey(db_column='cr_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters_created', to='users.user')),
                ('institution', models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.institution')),
                ('mod_by', models.ForeignKey(db_column='mod_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters_modified', to='users.user')),
                ('paper', models.ForeignKey(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.papersmaster', to_field='paper_id')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='enrollment.subjectmaster', to_field='subject_id')),
            ],
            options={
                'db_table': 'chapter_mast',
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
