# Generated by Django 4.2.30 on 2026-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermaster',
            name='chapter_short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
