# Generated by Django 4.2.30 on 2026-05-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_chaptermaster_chapter_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningunit',
            options={'ordering': ['lu_id']},
        ),
        migrations.AddField(
            model_name='learningunit',
            name='chapter',
            field=models.ForeignKey(blank=True, db_column='chapter_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='enrollment.chaptermaster', to_field='chapter_id'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='enrollment.subjectmaster', to_field='subject_id'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='course',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='enrollment.coursemaster', to_field='course_id'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='learning_unit_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='lu_caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='papersmaster',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papersmaster',
            name='modified_by',
            field=models.CharField(blank=True, default=None, max_length=50),
            preserve_default=False,
        ),
    ]
